"""Lightweight XRD preprocessing API."""

from .agbh import (
    AGBH_D_SPACING_NM,
    AG_KBETA_TO_KALPHA_Q_RATIO,
    AgBHMonochromaticityFilter,
    AgBHMonochromaticityQualityControl,
    AgBHMonochromaticityResult,
    AgBHMonochromaticitySelection,
    AgBHMonochromaticityScorer,
    agbh_alpha_peaks,
    agbh_kbeta_windows,
    calculate_agbh_monochromaticity,
)
from .azimuthal import AzimuthalIntegration, perform_azimuthal_integration
from .filters import (
    ColumnValueFilter,
    MetadataFilter,
    PatientFilter,
    PatientSpecimenValidityFilter,
    SNRFilter,
)
from .h5 import H5SessionFilter, filter_h5_sessions, h5_to_df, list_h5_sessions
from .faulty_pixels import (
    FAULTY_REASON_CODES,
    FAULTY_REASON_NEGATIVE,
    FAULTY_REASON_NONFINITE,
    FAULTY_REASON_OK,
    FAULTY_REASON_SATURATED,
    FaultyPixelDetector,
    HotPixelDetector,
    count_faulty_pixel_reasons,
    create_faulty_pixel_reason_map,
    create_mask,
    detect_faulty_pixels,
    detect_hot_pixels,
)
from .normalization import QRangeNormalizer, normalize_profile_by_q_range
from .gfrm import (
    decode_gfrm,
    extract_gfrm_archive,
    gfrm_conversion_metadata,
    gfrm_to_photons,
    parse_bruker_header_preview,
    parse_gfrm_header,
    read_gfrm_adu,
    read_gfrm_as_photons,
    read_gfrm_with_fabio,
    save_gfrm_as_npy,
    validate_gfrm_array,
)
from .snr import SNRTransformer, calculate_snr
from .snapshots import RadialProfileSnapshot

__all__ = [
    "AzimuthalIntegration",
    "AGBH_D_SPACING_NM",
    "AG_KBETA_TO_KALPHA_Q_RATIO",
    "AgBHMonochromaticityFilter",
    "AgBHMonochromaticityQualityControl",
    "AgBHMonochromaticityResult",
    "AgBHMonochromaticitySelection",
    "AgBHMonochromaticityScorer",
    "ColumnValueFilter",
    "FAULTY_REASON_CODES",
    "FAULTY_REASON_NEGATIVE",
    "FAULTY_REASON_NONFINITE",
    "FAULTY_REASON_OK",
    "FAULTY_REASON_SATURATED",
    "FaultyPixelDetector",
    "H5SessionFilter",
    "HotPixelDetector",
    "MetadataFilter",
    "PatientFilter",
    "PatientSpecimenValidityFilter",
    "QRangeNormalizer",
    "RadialProfileSnapshot",
    "SNRFilter",
    "SNRTransformer",
    "agbh_alpha_peaks",
    "agbh_kbeta_windows",
    "calculate_snr",
    "calculate_agbh_monochromaticity",
    "count_faulty_pixel_reasons",
    "create_faulty_pixel_reason_map",
    "create_mask",
    "detect_faulty_pixels",
    "detect_hot_pixels",
    "decode_gfrm",
    "extract_gfrm_archive",
    "gfrm_conversion_metadata",
    "gfrm_to_photons",
    "filter_h5_sessions",
    "h5_to_df",
    "list_h5_sessions",
    "normalize_profile_by_q_range",
    "parse_bruker_header_preview",
    "parse_gfrm_header",
    "perform_azimuthal_integration",
    "read_gfrm_adu",
    "read_gfrm_as_photons",
    "read_gfrm_with_fabio",
    "save_gfrm_as_npy",
    "validate_gfrm_array",
]
